Feature issue 3 add support for face/plane/hand/etc features of ar foundation
youar/upm-xrremote pull request #17
Opened 2023-03-28 07:49 UTC by duc55

Added support for plane tracking and touch input on phone device to Unity client.  Also, incorporated fixes for NullReferenceException on AR Remote Server script that was preventing camera data from being sent.

# PR Summary 
## (feat) Plane Detection ##
Added AR Plane Manager component to AR Session Origin.  The XRRemoteServer queries the plane manager for an array of the detected planes and serializes the AR Planes to XR Planes and send them to the client.  The Client contains an XRRemotePlaneManager uses that data to create planes using the pose and boundary points.  The XRRemotePlaneVisual shows the planes and the center point.  

## (feat) Touch Input ##
Added AR Raycast Manager and imported the new InputSystem.  When the Player Input detects Touch event, the XRRemoteInputReader saves the position of the touch (both as raw canvas coordinates and normalized) and the XRRemoteServer sends it to the client.  The XRRemoteInputSystem saves the touch position scaled to Unity player's canvas size and broadcasts a OnTouch event.  For debugging purposes, an ObjectSpawner creates a sphere object the the touch hits a plane and XRRemoteTouchVisual draws a white square at the last touch position.

## fix: Set reference to AR Pose Driver on XR Remote Server ##
Also, combined changes from PR #16 
Replaced the Tracked Posed Driver with AR Pose Driver in AR Remote Server scene.
Removed obsolete meta file.

Refs: #15  #3 

## QA Summary 

## :ledger: Notes

No additional notes were given.

## :chart_with_downwards_trend: Logs

No (crash) logs were given. 

#### Build Status

- [x] Build Passes ✅ 
- [x] Build Fails :x: 
--->

2023-03-28 20:10 UTC, gblikas commented
> Added AR Raycast Manager and imported the new InputSystem. When the Player Input detects Touch event, the XRRemoteInputReader saves the position of the touch (both as raw canvas coordinates and normalized) and the XRRemoteServer sends it to the client.

@duc55 with this explanation, it seems like InputSystem events are happening both on the client device as well as the editor; e.g. if I click on the phone for a ray-cast, i successfully ray-cast at the phone, but never transmit that exact ray-cast_ed_ position to the editor.

2023-03-28 20:14 UTC, duc55 commented
>  if I click on the phone for a ray-cast, i successfully ray-cast at the phone, but never transmit that exact ray-cast_ed_ position to the editor.

@gblikas  The raycast is only happening in the Unity editor.  The phone is only used to get the touch position.   

It would be possible to send AR Raycast info transfer in the future though.

2023-03-28 20:17 UTC, gblikas commented on Assets/Runtime/Resources/Input/ARController.inputactions
@duc55 what is this file? I'm not familiar with the `.inputactions` extension. Is it necessary for this PR?

2023-03-28 20:19 UTC, duc55 commented on Assets/Runtime/Resources/Input/ARController.inputactions
@gblikas .inputactions is used by the InputSystem to define which inputs we are watching for.  In this case, the Touch event.

2023-03-28 20:42 UTC, gblikas requested changes
@duc55 please see conversations for changes, and re-submit for PR approval.

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/AddObjectOnClient.cs
> +            XRRemote.XRRemoteInputSystem.Instance.OnTouch += XRRemoteInputSystem_OnTouch;
@duc55 There is a possibility that `OnTouch` may be called many times (at least more than once, for each event) if the UnityEditor is started and stopped multiple times. Make sure to check for non-null and remove the callback, if needed, e.g. 


```csharp
private void Awake()
{
    // Check if the event is already subscribed to
    if (XRRemote.XRRemoteInputSystem.Instance != null)
    {
        XRRemote.XRRemoteInputSystem.Instance.OnTouch -= OnTouch;
    }

    // Subscribe to the event
    XRRemote.XRRemoteInputSystem.Instance.OnTouch += OnTouch;
}

private void OnDestroy()
{
    // Unsubscribe from the event
    XRRemote.XRRemoteInputSystem.Instance.OnTouch -= OnTouch;
}
```

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/AddObjectOnInput.cs
@duc55 If this script was just used for testing, please remove for PR.

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Resources/XRPlaneCenterVisual.prefab
@duc55 If this was used just to test, please remove before PR.

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/XRRemoteInputSystem.cs
> +                Debug.LogError($"There's more than one XRRemoteInputSystem! " + transform + " = " + Instance);
@duc55 Please make sure to guard the `Debug` statement! For example, 

```csharp
if (DebugFlags.displayXRRemoteConnectionStats)
{
    Debug.LogErrorFormat(
        XRRemoteConnectionMessage(
            string.Format("TrySetUpXRRemotePlaneManager Event: null XRRemotePlaneManager")));
    return;
}
```

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/XRRemotePlaneManager.cs
> +                    if (planes[i].isSubsumed) continue;
@duc55 Try experiment with deleting `isSubsumed == true` planes. I think it might read clearer, if you just go ahead and delete them outright, instead of `xrRemotePlaneVisual.gameObject.SetActive(false);`

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/XRRemoteServer.cs
> +                if (log)
@duc55 Could you check on the other `guard` comment I have to see if they share with that? It would be great to get them using the same "Debug" guards.

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/XRRemoteTouchVisual.cs
> +            XRRemoteInputSystem.Instance.OnTouch += XRRemoteInputSystem_OnTouch;
@duc55 Same thing about subscribing and multiple calls. Please make sure you're checking whether or not you've already assigned the callback to the event you'd like to fire on.

2023-03-28 20:42 UTC, gblikas commented on Assets/Runtime/Scripts/XRRemoteTouchVisual.cs
@duc55 Spend some time looking for a nice asset for this; look at material design guidelines, or other application that do touch events, and see if you can copy their design, but not lose precision of what you want. Perhaps this is already capsulated in Unity Gizmos.

2023-03-28 22:58 UTC, duc55 commented on Assets/Runtime/Scripts/AddObjectOnClient.cs
> +            XRRemote.XRRemoteInputSystem.Instance.OnTouch += XRRemoteInputSystem_OnTouch;
@gblikas Added unsubscribe to OnDisable event.

2023-03-28 22:59 UTC, duc55 commented on Assets/Runtime/Scripts/AddObjectOnInput.cs
@gblikas Removed testing prefabs and scripts

2023-03-28 22:59 UTC, duc55 commented on Assets/Runtime/Resources/XRPlaneCenterVisual.prefab
@gblikas Removed testing prefabs and scripts

2023-03-28 23:20 UTC, duc55 commented on Assets/Runtime/Scripts/XRRemoteServer.cs
> +                if (log)
@gblikas There seems to be 2 debug guards
```csharp
if (DebugFlags.displayXRRemoteConnectionStats) ...
```
for connection errors
```csharp
if (log) ...
```
for warning and missing components

2023-03-28 23:26 UTC, duc55 commented on Assets/Runtime/Scripts/XRRemoteTouchVisual.cs
> +            XRRemoteInputSystem.Instance.OnTouch += XRRemoteInputSystem_OnTouch;
@gblikas Added unsubscribing to ToDisable event

2023-03-28 23:57 UTC, gblikas commented on Assets/Runtime/Scripts/XRRemoteServer.cs
> +                if (log)
@duc55 Which of those do you think we should use?

2023-03-29 00:00 UTC, duc55 commented on Assets/Runtime/Scripts/XRRemoteTouchVisual.cs
@gblikas Changed the touch indicator to a circular blip that you see on some phones.

2023-03-29 22:08 UTC, duc55 commented on Assets/Runtime/Scripts/XRRemoteServer.cs
> +                if (log)
It looks like log is used to reduce the number of errors being reported depending if the log level is set to verbose or minimal.  It might be nice to have for warning or informative outputs and then have DebugFlags for errors in the setup.

2023-03-30 09:04 UTC, duc55 commented on Assets/Runtime/Scripts/XRRemotePlaneManager.cs
> +                    if (planes[i].isSubsumed) continue;
@gblikas Updated so that the server is only sending plane events when planes get add, updated, or removed instead sending plane data every frame.  It should be much more readable now.

2023-03-30 17:27 UTC, gblikas commented on Assets/Runtime/Scripts/XRPlane.cs
> +        public ARKitStream.Internal.TrackableId trackableId;
@duc55 What is this type?

2023-03-30 19:50 UTC, duc55 commented on Assets/Runtime/Scripts/XRPlane.cs
> +        public ARKitStream.Internal.TrackableId trackableId;
This is the serializable version of the TrackableId used in AR Foundation.

2023-03-30 19:52 UTC, gblikas commented on Assets/Runtime/Scripts/XRPlane.cs
> +        public ARKitStream.Internal.TrackableId trackableId;
That looks to be `ARKit` specific... Is there a non-`ARKit` specific version?

2023-03-30 19:57 UTC, duc55 commented on Assets/Runtime/Scripts/XRPlane.cs
> +        public ARKitStream.Internal.TrackableId trackableId;
I think its based on the AR Kit Stream project that you sent me previously.  The namespace could probably be changed to XRRemote like the rest of the project.  It looks like its only used in the plane and face scripts.

2023-03-30 20:35 UTC, duc55 commented on Assets/Runtime/Scripts/XRPlane.cs
> +        public ARKitStream.Internal.TrackableId trackableId;
Updated the namespace to XRRemote.

2023-03-31 17:53 UTC, gblikas approved these changes

2023-03-31 17:53 UTC, gblikas approved these changes

2023-03-31 17:56 UTC, merged