Feature issue 25 fps optimization
youar/upm-xrremote pull request #31
Opened 2023-07-03 21:56 UTC by AsheUrban

# PR Summary 

This PR addresses issues outlined in issue #25, namely the addition of of Custom Plane Manager.

#### Build Status
- [x] Build Passes ✅

2023-07-03 22:02 UTC, AsheUrban commented
Hello, @gblikas would you mind giving this a review? Thanks!

2023-07-03 22:50 UTC, gblikas requested changes
@AsheUrban Overall a huge improvement in speed, as tested! While this does improve #25 , we do need to do a bit of project cleanup: 
- `Assets/Runtime/Materials/<Red,Blue,Green>*` (teal looks like it's still used in XRRemotePlaneManager - however I cannot find any references to it in scene) 
- Prefab `XR Remote Connection` should be deleted or moved to archive since it's no longer being used. 
- `Assets/Runtime/Prefabs/AR Default Sphere` should be deleted or moved to archive.
- `Assets/Runtime/Resources/*` should be deleted or moved to archive. 
- `Assets/Runtime/Scripts/Serializables/XRPlane` has a name mis-match with the type "XRPlaneNdi" (name of the class is not the name of the file) 
- `Assets/Runtime/Scripts/Serializables/<PlanesInfo.cs,CameraFrameEvent.cs>` are missing copywrite header 
- Prefix all `Assets/Runtime/Scripts/Serializables/` with "Serializable", so that ppl using those classes know that they should be safe to read/write. 
- `Assets/Runtime/Scripts` should contain only scripts used in _both_ receiving and sending. Whereas `Assets/Runtime/Scripts/<Server,Client>` should be specific to use-case. See `/Plan.md`
- `Assets/Runtime/Scripts/*` need a copywrite header. 
- Make use of prefabs for `NDI Sender` and `NDI Receiver`; when ppl pull in upm-xrremote, they're going to need to streamline their project setup: e.g. I have an AR App, I want to debug, I install upm-xrremote, then drag in the NDI Receiver prefab into my scene and then it's setup to catch any sent data.

2023-07-14 06:52 UTC, duc55 commented
@gblikas Changes are completed.  
Bidirectional sender still needs to be completed to send UI Camera data.

2023-07-25 17:49 UTC, gblikas approved these changes

2023-07-25 17:57 UTC, merged