add SetupTools to auto add Planes and XRRemote-Debug layers on editor…
youar/upm-xrremote pull request #42
Opened 2023-08-03 18:05 UTC by Razieleron

SetupTools.cs runs a script on editor load to add Plane and XRRemote-Debug to the layers list. Additionally, there is a menu button called 'Tools' with an option to 'Setup Layers' which does the same thing, but you shouldn't have to click it since the method is run on editor startup. We can add additional functionality to this later if we want.

There is some error handling in the creation of the layers to make sure we're not overwriting an already labeled layer (we just target the next unlabeled layer) and an error log if for some reason there are no available layers whatsoever.

2023-08-03 22:46 UTC, CarlSustrich reviewed
Looks solid! 
Discovered, if the 'culling mask' feature on the camera component of the ARCamera object is set to 'mixed', the created layers will not automatically be added. I'd imagine our optimal solution would involve automatically enabling these layers in the ARCamera upon creation. Seems too fiddly for end user to need to go enable them themselves?
[This](https://docs.unity3d.com/ScriptReference/Camera-cullingMask.html) method could be pertinent. Would need to make sure we're only targeting the AR Camera to add the layers to, not a standard UI camera or similar.

2023-08-04 19:42 UTC, gblikas commented
> Discovered, if the 'culling mask' feature on the camera component of the ARCamera object is set to 'mixed', the created layers will not automatically be added. I'd imagine our optimal solution would involve automatically enabling these layers in the ARCamera upon creation. Seems too fiddly for end user to need to go enable them themselves?

@Razieleron yes, please make sure that the layers you added are being rendered after adding.

2023-08-07 16:20 UTC, Razieleron commented
@gblikas wrapped up that culling mask issue.

2023-08-08 06:40 UTC, gblikas requested changes
@Razieleron took a look at the code and it looks like a couple changes are needed. 
1. please make sure that all files have our License agreement at the top. 
2. make sure any sources that were used to create the code are cited. 
3. the SetupTools functionality shouldn't be split between `XRRemote/Layer Utilities/Create Layers` and `XRRemote/Layer Utilities/Setup Camera Culling Mask`. if you're setting up the project, it should make sure that layers _and_ the culling mask is setup.

2023-08-08 20:36 UTC, Razieleron commented
The code now successfully targets all AR cameras in the hierarchy and sets their culling mask. 

Upon thinking about it, Carl and I figured that it could get obnoxious for the end user if the Planes and XRRemote-Debug layers were set to checked on all AR cameras on every script recompilation/editor refresh and so we localized that functionality to the XRRemote -> Layer Utilities -> Create Layers and Setup Camera Culling Mask button in the menu.

If you would like it to be set up differently, please let me know.

2023-08-11 22:25 UTC, CarlSustrich submitted a review, later dismissed
New changes - adds layers to culling mask directly after creating them, and this only occurs on menu item select by user, not automatically on load. Looks good to me 🤘

2023-08-11 22:36 UTC, gblikas requested changes

2023-08-11 22:36 UTC, gblikas commented on Assets/Editor/SetupTools.cs
> +using System.Runtime.CompilerServices;
using statement needs to go below license statement

2023-08-11 22:42 UTC, Razieleron commented on Assets/Editor/SetupTools.cs
> +using System.Runtime.CompilerServices;
I've moved them below the license statement-

2023-08-11 22:44 UTC, gblikas approved these changes

2023-08-11 22:52 UTC, merged