Feature issue 24 add support for image recognition
youar/upm-xrremote pull request #48
Opened 2023-09-11 20:14 UTC by CarlSustrich

# PR Summary 

This PR closes github issue #24. Implements image recognition capabilities. 

## QA Summary 

Tested in Android environment.
Test hardware:
Pixel 7, Android 13 OS, 8GB ram. 

## :ledger: Notes

Due to a major discrepancy between scene setup when this branch was created, and the new structure with the prefab consolidated into a single GameObject, a subsequent PR may be necessary to appropriately incorporate the relevant components. 

#### Build Status

- [x] Build Passes ✅

2023-09-11 23:09 UTC, gblikas requested changes
Please see comments about `new Texture`.

2023-09-11 23:09 UTC, gblikas commented on Assets/Runtime/Scripts/Client/ImageRec/XRRemoteImageManager.cs
> +            var tex = new Texture2D((int)foundImage.texSize.x, (int)foundImage.texSize.y, (TextureFormat)Enum.Parse(typeof(TextureFormat), foundImage.texFormat), false);
@CarlSustrich since you are creating a `new Texture2D` you will need to have some method for destroy the texture; pooling might be a good option here.

2023-09-11 23:09 UTC, gblikas commented on Assets/Runtime/Scripts/Serializables/SerializableXRReferenceImage.cs
> +            Texture2D tex = new Texture2D((int)texSize.x, (int)texSize.y, (TextureFormat)Enum.Parse(typeof(TextureFormat), texFormat), true);
@CarlSustrich same here*

2023-09-11 23:09 UTC, gblikas commented on Assets/Runtime/Scripts/Server/ImageRec/TestImageRecScript.cs
@CarlSustrich this script should be removed, or `ifdef`’d accordingly.

2023-09-12 21:29 UTC, CarlSustrich commented on Assets/Runtime/Scripts/Client/ImageRec/XRRemoteImageManager.cs
> +            var tex = new Texture2D((int)foundImage.texSize.x, (int)foundImage.texSize.y, (TextureFormat)Enum.Parse(typeof(TextureFormat), foundImage.texFormat), false);
Added.

2023-09-12 21:30 UTC, CarlSustrich commented on Assets/Runtime/Scripts/Server/ImageRec/TestImageRecScript.cs
Deleted accidentally pushed file.

2023-09-12 21:33 UTC, gblikas commented on Assets/Runtime/Scripts/Serializables/SerializableXRReferenceImage.cs
> -            //[Review] true here indicates texture should be made in linear color space. is this appropriate?
@CarlSustrich i didn’t catch this comment the first time around - we might need to investigate this more at a later stage, based on our other projects.

2023-09-12 21:33 UTC, gblikas approved these changes
We’ll continue via Discord.

2023-09-12 21:44 UTC, merged